//
// Created by Griffin Prechter on 11/13/20.
//

#ifndef YOUVERIFY_TRANSFORM_H
#define YOUVERIFY_TRANSFORM_H
#include "AST/Instruction.h"
#include "SymbolTable.h"

INSTRUCTION transformINSTRUCTION(INSTRUCTION instruction, SYMBOL_TABLE *table);

GOTO_INSTRUCTION transformGOTO_INSTRUCTION(GOTO_INSTRUCTION instruction, SYMBOL_TABLE *table);

ASSIGNMENT_INSTRUCTION transformASSIGNMENT_INSTRUCTION(ASSIGNMENT_INSTRUCTION instruction, SYMBOL_TABLE *table);

DECLARATION_INSTRUCTION transformDECLARATION_INSTRUCTION(DECLARATION_INSTRUCTION instruction, SYMBOL_TABLE *table);

EXPRESSION transformEXPRESSION(EXPRESSION expression, SYMBOL_TABLE *table);

BINARY_EXPRESSION transformBINARY_EXPRESSION(BINARY_EXPRESSION expression, SYMBOL_TABLE *table);

UNARY_EXPRESSION transformUNARY_EXPRESSION(UNARY_EXPRESSION expression, SYMBOL_TABLE *table);

TERNARY_EXPRESSION transformTERNARY_EXPRESSION(TERNARY_EXPRESSION expression, SYMBOL_TABLE *table);

ATOMIC_EXPRESSION transformATOMIC_EXPRESSION(ATOMIC_EXPRESSION expression, SYMBOL_TABLE *table);

#endif //YOUVERIFY_TRANSFORM_H
