name: Continuous Integration

on:
  pull_request:
  push:

jobs:
  test:
    name: test
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          make -j4

      - name: Run On Examples
        run: |
          cd test
          ../build/youverify tests/add.yvr
          ../build/youverify tests/sub.yvr

      - name: Tests
        run: |
          cd test
          ./run_tests.sh
