name: Continuous Integration

on:
  pull_request:
  push:

jobs:
  test:
    name: test
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          make -j4

      - name: Test
        run: |
          echo "TODO"
